/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.16.8+97-gee14285
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.gitea.model;

import java.util.Objects;
import com.gitea.model.ExternalTracker;
import com.gitea.model.ExternalWiki;
import com.gitea.model.InternalTracker;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * EditRepoOption options when editing a repository&#39;s properties
 */
@ApiModel(description = "EditRepoOption options when editing a repository's properties")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2022-07-07T10:42:04.488+08:00")
public class EditRepoOption   {
  @SerializedName("allow_manual_merge")
  private Boolean allowManualMerge = null;

  @SerializedName("allow_merge_commits")
  private Boolean allowMergeCommits = null;

  @SerializedName("allow_rebase")
  private Boolean allowRebase = null;

  @SerializedName("allow_rebase_explicit")
  private Boolean allowRebaseExplicit = null;

  @SerializedName("allow_squash_merge")
  private Boolean allowSquashMerge = null;

  @SerializedName("archived")
  private Boolean archived = null;

  @SerializedName("autodetect_manual_merge")
  private Boolean autodetectManualMerge = null;

  @SerializedName("default_branch")
  private String defaultBranch = null;

  @SerializedName("default_delete_branch_after_merge")
  private Boolean defaultDeleteBranchAfterMerge = null;

  @SerializedName("default_merge_style")
  private String defaultMergeStyle = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("enable_prune")
  private Boolean enablePrune = null;

  @SerializedName("external_tracker")
  private ExternalTracker externalTracker = null;

  @SerializedName("external_wiki")
  private ExternalWiki externalWiki = null;

  @SerializedName("has_issues")
  private Boolean hasIssues = null;

  @SerializedName("has_projects")
  private Boolean hasProjects = null;

  @SerializedName("has_pull_requests")
  private Boolean hasPullRequests = null;

  @SerializedName("has_wiki")
  private Boolean hasWiki = null;

  @SerializedName("ignore_whitespace_conflicts")
  private Boolean ignoreWhitespaceConflicts = null;

  @SerializedName("internal_tracker")
  private InternalTracker internalTracker = null;

  @SerializedName("mirror_interval")
  private String mirrorInterval = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("private")
  private Boolean _private = null;

  @SerializedName("template")
  private Boolean template = null;

  @SerializedName("website")
  private String website = null;

  public EditRepoOption allowManualMerge(Boolean allowManualMerge) {
    this.allowManualMerge = allowManualMerge;
    return this;
  }

   /**
   * either `true` to allow mark pr as merged manually, or `false` to prevent it. `has_pull_requests` must be `true`.
   * @return allowManualMerge
  **/
  @ApiModelProperty(example = "null", value = "either `true` to allow mark pr as merged manually, or `false` to prevent it. `has_pull_requests` must be `true`.")
  public Boolean getAllowManualMerge() {
    return allowManualMerge;
  }

  public void setAllowManualMerge(Boolean allowManualMerge) {
    this.allowManualMerge = allowManualMerge;
  }

  public EditRepoOption allowMergeCommits(Boolean allowMergeCommits) {
    this.allowMergeCommits = allowMergeCommits;
    return this;
  }

   /**
   * either `true` to allow merging pull requests with a merge commit, or `false` to prevent merging pull requests with merge commits. `has_pull_requests` must be `true`.
   * @return allowMergeCommits
  **/
  @ApiModelProperty(example = "null", value = "either `true` to allow merging pull requests with a merge commit, or `false` to prevent merging pull requests with merge commits. `has_pull_requests` must be `true`.")
  public Boolean getAllowMergeCommits() {
    return allowMergeCommits;
  }

  public void setAllowMergeCommits(Boolean allowMergeCommits) {
    this.allowMergeCommits = allowMergeCommits;
  }

  public EditRepoOption allowRebase(Boolean allowRebase) {
    this.allowRebase = allowRebase;
    return this;
  }

   /**
   * either `true` to allow rebase-merging pull requests, or `false` to prevent rebase-merging. `has_pull_requests` must be `true`.
   * @return allowRebase
  **/
  @ApiModelProperty(example = "null", value = "either `true` to allow rebase-merging pull requests, or `false` to prevent rebase-merging. `has_pull_requests` must be `true`.")
  public Boolean getAllowRebase() {
    return allowRebase;
  }

  public void setAllowRebase(Boolean allowRebase) {
    this.allowRebase = allowRebase;
  }

  public EditRepoOption allowRebaseExplicit(Boolean allowRebaseExplicit) {
    this.allowRebaseExplicit = allowRebaseExplicit;
    return this;
  }

   /**
   * either `true` to allow rebase with explicit merge commits (--no-ff), or `false` to prevent rebase with explicit merge commits. `has_pull_requests` must be `true`.
   * @return allowRebaseExplicit
  **/
  @ApiModelProperty(example = "null", value = "either `true` to allow rebase with explicit merge commits (--no-ff), or `false` to prevent rebase with explicit merge commits. `has_pull_requests` must be `true`.")
  public Boolean getAllowRebaseExplicit() {
    return allowRebaseExplicit;
  }

  public void setAllowRebaseExplicit(Boolean allowRebaseExplicit) {
    this.allowRebaseExplicit = allowRebaseExplicit;
  }

  public EditRepoOption allowSquashMerge(Boolean allowSquashMerge) {
    this.allowSquashMerge = allowSquashMerge;
    return this;
  }

   /**
   * either `true` to allow squash-merging pull requests, or `false` to prevent squash-merging. `has_pull_requests` must be `true`.
   * @return allowSquashMerge
  **/
  @ApiModelProperty(example = "null", value = "either `true` to allow squash-merging pull requests, or `false` to prevent squash-merging. `has_pull_requests` must be `true`.")
  public Boolean getAllowSquashMerge() {
    return allowSquashMerge;
  }

  public void setAllowSquashMerge(Boolean allowSquashMerge) {
    this.allowSquashMerge = allowSquashMerge;
  }

  public EditRepoOption archived(Boolean archived) {
    this.archived = archived;
    return this;
  }

   /**
   * set to `true` to archive this repository.
   * @return archived
  **/
  @ApiModelProperty(example = "null", value = "set to `true` to archive this repository.")
  public Boolean getArchived() {
    return archived;
  }

  public void setArchived(Boolean archived) {
    this.archived = archived;
  }

  public EditRepoOption autodetectManualMerge(Boolean autodetectManualMerge) {
    this.autodetectManualMerge = autodetectManualMerge;
    return this;
  }

   /**
   * either `true` to enable AutodetectManualMerge, or `false` to prevent it. `has_pull_requests` must be `true`, Note: In some special cases, misjudgments can occur.
   * @return autodetectManualMerge
  **/
  @ApiModelProperty(example = "null", value = "either `true` to enable AutodetectManualMerge, or `false` to prevent it. `has_pull_requests` must be `true`, Note: In some special cases, misjudgments can occur.")
  public Boolean getAutodetectManualMerge() {
    return autodetectManualMerge;
  }

  public void setAutodetectManualMerge(Boolean autodetectManualMerge) {
    this.autodetectManualMerge = autodetectManualMerge;
  }

  public EditRepoOption defaultBranch(String defaultBranch) {
    this.defaultBranch = defaultBranch;
    return this;
  }

   /**
   * sets the default branch for this repository.
   * @return defaultBranch
  **/
  @ApiModelProperty(example = "null", value = "sets the default branch for this repository.")
  public String getDefaultBranch() {
    return defaultBranch;
  }

  public void setDefaultBranch(String defaultBranch) {
    this.defaultBranch = defaultBranch;
  }

  public EditRepoOption defaultDeleteBranchAfterMerge(Boolean defaultDeleteBranchAfterMerge) {
    this.defaultDeleteBranchAfterMerge = defaultDeleteBranchAfterMerge;
    return this;
  }

   /**
   * set to `true` to delete pr branch after merge by default
   * @return defaultDeleteBranchAfterMerge
  **/
  @ApiModelProperty(example = "null", value = "set to `true` to delete pr branch after merge by default")
  public Boolean getDefaultDeleteBranchAfterMerge() {
    return defaultDeleteBranchAfterMerge;
  }

  public void setDefaultDeleteBranchAfterMerge(Boolean defaultDeleteBranchAfterMerge) {
    this.defaultDeleteBranchAfterMerge = defaultDeleteBranchAfterMerge;
  }

  public EditRepoOption defaultMergeStyle(String defaultMergeStyle) {
    this.defaultMergeStyle = defaultMergeStyle;
    return this;
  }

   /**
   * set to a merge style to be used by this repository: \"merge\", \"rebase\", \"rebase-merge\", or \"squash\". `has_pull_requests` must be `true`.
   * @return defaultMergeStyle
  **/
  @ApiModelProperty(example = "null", value = "set to a merge style to be used by this repository: \"merge\", \"rebase\", \"rebase-merge\", or \"squash\". `has_pull_requests` must be `true`.")
  public String getDefaultMergeStyle() {
    return defaultMergeStyle;
  }

  public void setDefaultMergeStyle(String defaultMergeStyle) {
    this.defaultMergeStyle = defaultMergeStyle;
  }

  public EditRepoOption description(String description) {
    this.description = description;
    return this;
  }

   /**
   * a short description of the repository.
   * @return description
  **/
  @ApiModelProperty(example = "null", value = "a short description of the repository.")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public EditRepoOption enablePrune(Boolean enablePrune) {
    this.enablePrune = enablePrune;
    return this;
  }

   /**
   * enable prune - remove obsolete remote-tracking references
   * @return enablePrune
  **/
  @ApiModelProperty(example = "null", value = "enable prune - remove obsolete remote-tracking references")
  public Boolean getEnablePrune() {
    return enablePrune;
  }

  public void setEnablePrune(Boolean enablePrune) {
    this.enablePrune = enablePrune;
  }

  public EditRepoOption externalTracker(ExternalTracker externalTracker) {
    this.externalTracker = externalTracker;
    return this;
  }

   /**
   * Get externalTracker
   * @return externalTracker
  **/
  @ApiModelProperty(example = "null", value = "")
  public ExternalTracker getExternalTracker() {
    return externalTracker;
  }

  public void setExternalTracker(ExternalTracker externalTracker) {
    this.externalTracker = externalTracker;
  }

  public EditRepoOption externalWiki(ExternalWiki externalWiki) {
    this.externalWiki = externalWiki;
    return this;
  }

   /**
   * Get externalWiki
   * @return externalWiki
  **/
  @ApiModelProperty(example = "null", value = "")
  public ExternalWiki getExternalWiki() {
    return externalWiki;
  }

  public void setExternalWiki(ExternalWiki externalWiki) {
    this.externalWiki = externalWiki;
  }

  public EditRepoOption hasIssues(Boolean hasIssues) {
    this.hasIssues = hasIssues;
    return this;
  }

   /**
   * either `true` to enable issues for this repository or `false` to disable them.
   * @return hasIssues
  **/
  @ApiModelProperty(example = "null", value = "either `true` to enable issues for this repository or `false` to disable them.")
  public Boolean getHasIssues() {
    return hasIssues;
  }

  public void setHasIssues(Boolean hasIssues) {
    this.hasIssues = hasIssues;
  }

  public EditRepoOption hasProjects(Boolean hasProjects) {
    this.hasProjects = hasProjects;
    return this;
  }

   /**
   * either `true` to enable project unit, or `false` to disable them.
   * @return hasProjects
  **/
  @ApiModelProperty(example = "null", value = "either `true` to enable project unit, or `false` to disable them.")
  public Boolean getHasProjects() {
    return hasProjects;
  }

  public void setHasProjects(Boolean hasProjects) {
    this.hasProjects = hasProjects;
  }

  public EditRepoOption hasPullRequests(Boolean hasPullRequests) {
    this.hasPullRequests = hasPullRequests;
    return this;
  }

   /**
   * either `true` to allow pull requests, or `false` to prevent pull request.
   * @return hasPullRequests
  **/
  @ApiModelProperty(example = "null", value = "either `true` to allow pull requests, or `false` to prevent pull request.")
  public Boolean getHasPullRequests() {
    return hasPullRequests;
  }

  public void setHasPullRequests(Boolean hasPullRequests) {
    this.hasPullRequests = hasPullRequests;
  }

  public EditRepoOption hasWiki(Boolean hasWiki) {
    this.hasWiki = hasWiki;
    return this;
  }

   /**
   * either `true` to enable the wiki for this repository or `false` to disable it.
   * @return hasWiki
  **/
  @ApiModelProperty(example = "null", value = "either `true` to enable the wiki for this repository or `false` to disable it.")
  public Boolean getHasWiki() {
    return hasWiki;
  }

  public void setHasWiki(Boolean hasWiki) {
    this.hasWiki = hasWiki;
  }

  public EditRepoOption ignoreWhitespaceConflicts(Boolean ignoreWhitespaceConflicts) {
    this.ignoreWhitespaceConflicts = ignoreWhitespaceConflicts;
    return this;
  }

   /**
   * either `true` to ignore whitespace for conflicts, or `false` to not ignore whitespace. `has_pull_requests` must be `true`.
   * @return ignoreWhitespaceConflicts
  **/
  @ApiModelProperty(example = "null", value = "either `true` to ignore whitespace for conflicts, or `false` to not ignore whitespace. `has_pull_requests` must be `true`.")
  public Boolean getIgnoreWhitespaceConflicts() {
    return ignoreWhitespaceConflicts;
  }

  public void setIgnoreWhitespaceConflicts(Boolean ignoreWhitespaceConflicts) {
    this.ignoreWhitespaceConflicts = ignoreWhitespaceConflicts;
  }

  public EditRepoOption internalTracker(InternalTracker internalTracker) {
    this.internalTracker = internalTracker;
    return this;
  }

   /**
   * Get internalTracker
   * @return internalTracker
  **/
  @ApiModelProperty(example = "null", value = "")
  public InternalTracker getInternalTracker() {
    return internalTracker;
  }

  public void setInternalTracker(InternalTracker internalTracker) {
    this.internalTracker = internalTracker;
  }

  public EditRepoOption mirrorInterval(String mirrorInterval) {
    this.mirrorInterval = mirrorInterval;
    return this;
  }

   /**
   * set to a string like `8h30m0s` to set the mirror interval time
   * @return mirrorInterval
  **/
  @ApiModelProperty(example = "null", value = "set to a string like `8h30m0s` to set the mirror interval time")
  public String getMirrorInterval() {
    return mirrorInterval;
  }

  public void setMirrorInterval(String mirrorInterval) {
    this.mirrorInterval = mirrorInterval;
  }

  public EditRepoOption name(String name) {
    this.name = name;
    return this;
  }

   /**
   * name of the repository
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "name of the repository")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public EditRepoOption _private(Boolean _private) {
    this._private = _private;
    return this;
  }

   /**
   * either `true` to make the repository private or `false` to make it public. Note: you will get a 422 error if the organization restricts changing repository visibility to organization owners and a non-owner tries to change the value of private.
   * @return _private
  **/
  @ApiModelProperty(example = "null", value = "either `true` to make the repository private or `false` to make it public. Note: you will get a 422 error if the organization restricts changing repository visibility to organization owners and a non-owner tries to change the value of private.")
  public Boolean getPrivate() {
    return _private;
  }

  public void setPrivate(Boolean _private) {
    this._private = _private;
  }

  public EditRepoOption template(Boolean template) {
    this.template = template;
    return this;
  }

   /**
   * either `true` to make this repository a template or `false` to make it a normal repository
   * @return template
  **/
  @ApiModelProperty(example = "null", value = "either `true` to make this repository a template or `false` to make it a normal repository")
  public Boolean getTemplate() {
    return template;
  }

  public void setTemplate(Boolean template) {
    this.template = template;
  }

  public EditRepoOption website(String website) {
    this.website = website;
    return this;
  }

   /**
   * a URL with more information about the repository.
   * @return website
  **/
  @ApiModelProperty(example = "null", value = "a URL with more information about the repository.")
  public String getWebsite() {
    return website;
  }

  public void setWebsite(String website) {
    this.website = website;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EditRepoOption editRepoOption = (EditRepoOption) o;
    return Objects.equals(this.allowManualMerge, editRepoOption.allowManualMerge) &&
        Objects.equals(this.allowMergeCommits, editRepoOption.allowMergeCommits) &&
        Objects.equals(this.allowRebase, editRepoOption.allowRebase) &&
        Objects.equals(this.allowRebaseExplicit, editRepoOption.allowRebaseExplicit) &&
        Objects.equals(this.allowSquashMerge, editRepoOption.allowSquashMerge) &&
        Objects.equals(this.archived, editRepoOption.archived) &&
        Objects.equals(this.autodetectManualMerge, editRepoOption.autodetectManualMerge) &&
        Objects.equals(this.defaultBranch, editRepoOption.defaultBranch) &&
        Objects.equals(this.defaultDeleteBranchAfterMerge, editRepoOption.defaultDeleteBranchAfterMerge) &&
        Objects.equals(this.defaultMergeStyle, editRepoOption.defaultMergeStyle) &&
        Objects.equals(this.description, editRepoOption.description) &&
        Objects.equals(this.enablePrune, editRepoOption.enablePrune) &&
        Objects.equals(this.externalTracker, editRepoOption.externalTracker) &&
        Objects.equals(this.externalWiki, editRepoOption.externalWiki) &&
        Objects.equals(this.hasIssues, editRepoOption.hasIssues) &&
        Objects.equals(this.hasProjects, editRepoOption.hasProjects) &&
        Objects.equals(this.hasPullRequests, editRepoOption.hasPullRequests) &&
        Objects.equals(this.hasWiki, editRepoOption.hasWiki) &&
        Objects.equals(this.ignoreWhitespaceConflicts, editRepoOption.ignoreWhitespaceConflicts) &&
        Objects.equals(this.internalTracker, editRepoOption.internalTracker) &&
        Objects.equals(this.mirrorInterval, editRepoOption.mirrorInterval) &&
        Objects.equals(this.name, editRepoOption.name) &&
        Objects.equals(this._private, editRepoOption._private) &&
        Objects.equals(this.template, editRepoOption.template) &&
        Objects.equals(this.website, editRepoOption.website);
  }

  @Override
  public int hashCode() {
    return Objects.hash(allowManualMerge, allowMergeCommits, allowRebase, allowRebaseExplicit, allowSquashMerge, archived, autodetectManualMerge, defaultBranch, defaultDeleteBranchAfterMerge, defaultMergeStyle, description, enablePrune, externalTracker, externalWiki, hasIssues, hasProjects, hasPullRequests, hasWiki, ignoreWhitespaceConflicts, internalTracker, mirrorInterval, name, _private, template, website);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EditRepoOption {\n");
    
    sb.append("    allowManualMerge: ").append(toIndentedString(allowManualMerge)).append("\n");
    sb.append("    allowMergeCommits: ").append(toIndentedString(allowMergeCommits)).append("\n");
    sb.append("    allowRebase: ").append(toIndentedString(allowRebase)).append("\n");
    sb.append("    allowRebaseExplicit: ").append(toIndentedString(allowRebaseExplicit)).append("\n");
    sb.append("    allowSquashMerge: ").append(toIndentedString(allowSquashMerge)).append("\n");
    sb.append("    archived: ").append(toIndentedString(archived)).append("\n");
    sb.append("    autodetectManualMerge: ").append(toIndentedString(autodetectManualMerge)).append("\n");
    sb.append("    defaultBranch: ").append(toIndentedString(defaultBranch)).append("\n");
    sb.append("    defaultDeleteBranchAfterMerge: ").append(toIndentedString(defaultDeleteBranchAfterMerge)).append("\n");
    sb.append("    defaultMergeStyle: ").append(toIndentedString(defaultMergeStyle)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    enablePrune: ").append(toIndentedString(enablePrune)).append("\n");
    sb.append("    externalTracker: ").append(toIndentedString(externalTracker)).append("\n");
    sb.append("    externalWiki: ").append(toIndentedString(externalWiki)).append("\n");
    sb.append("    hasIssues: ").append(toIndentedString(hasIssues)).append("\n");
    sb.append("    hasProjects: ").append(toIndentedString(hasProjects)).append("\n");
    sb.append("    hasPullRequests: ").append(toIndentedString(hasPullRequests)).append("\n");
    sb.append("    hasWiki: ").append(toIndentedString(hasWiki)).append("\n");
    sb.append("    ignoreWhitespaceConflicts: ").append(toIndentedString(ignoreWhitespaceConflicts)).append("\n");
    sb.append("    internalTracker: ").append(toIndentedString(internalTracker)).append("\n");
    sb.append("    mirrorInterval: ").append(toIndentedString(mirrorInterval)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    _private: ").append(toIndentedString(_private)).append("\n");
    sb.append("    template: ").append(toIndentedString(template)).append("\n");
    sb.append("    website: ").append(toIndentedString(website)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

