/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.16.8+97-gee14285
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.gitea.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * NodeInfoUsageUsers contains statistics about the users of this server
 */
@ApiModel(description = "NodeInfoUsageUsers contains statistics about the users of this server")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2022-07-07T10:42:04.488+08:00")
public class NodeInfoUsageUsers   {
  @SerializedName("activeHalfyear")
  private Long activeHalfyear = null;

  @SerializedName("activeMonth")
  private Long activeMonth = null;

  @SerializedName("total")
  private Long total = null;

  public NodeInfoUsageUsers activeHalfyear(Long activeHalfyear) {
    this.activeHalfyear = activeHalfyear;
    return this;
  }

   /**
   * Get activeHalfyear
   * @return activeHalfyear
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getActiveHalfyear() {
    return activeHalfyear;
  }

  public void setActiveHalfyear(Long activeHalfyear) {
    this.activeHalfyear = activeHalfyear;
  }

  public NodeInfoUsageUsers activeMonth(Long activeMonth) {
    this.activeMonth = activeMonth;
    return this;
  }

   /**
   * Get activeMonth
   * @return activeMonth
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getActiveMonth() {
    return activeMonth;
  }

  public void setActiveMonth(Long activeMonth) {
    this.activeMonth = activeMonth;
  }

  public NodeInfoUsageUsers total(Long total) {
    this.total = total;
    return this;
  }

   /**
   * Get total
   * @return total
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getTotal() {
    return total;
  }

  public void setTotal(Long total) {
    this.total = total;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NodeInfoUsageUsers nodeInfoUsageUsers = (NodeInfoUsageUsers) o;
    return Objects.equals(this.activeHalfyear, nodeInfoUsageUsers.activeHalfyear) &&
        Objects.equals(this.activeMonth, nodeInfoUsageUsers.activeMonth) &&
        Objects.equals(this.total, nodeInfoUsageUsers.total);
  }

  @Override
  public int hashCode() {
    return Objects.hash(activeHalfyear, activeMonth, total);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NodeInfoUsageUsers {\n");
    
    sb.append("    activeHalfyear: ").append(toIndentedString(activeHalfyear)).append("\n");
    sb.append("    activeMonth: ").append(toIndentedString(activeMonth)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

