/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.16.8+97-gee14285
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.gitea.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * NodeInfoServices contains the third party sites this server can connect to via their application API
 */
@ApiModel(description = "NodeInfoServices contains the third party sites this server can connect to via their application API")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2022-07-07T10:42:04.488+08:00")
public class NodeInfoServices   {
  @SerializedName("inbound")
  private List<String> inbound = new ArrayList<String>();

  @SerializedName("outbound")
  private List<String> outbound = new ArrayList<String>();

  public NodeInfoServices inbound(List<String> inbound) {
    this.inbound = inbound;
    return this;
  }

  public NodeInfoServices addInboundItem(String inboundItem) {
    this.inbound.add(inboundItem);
    return this;
  }

   /**
   * Get inbound
   * @return inbound
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getInbound() {
    return inbound;
  }

  public void setInbound(List<String> inbound) {
    this.inbound = inbound;
  }

  public NodeInfoServices outbound(List<String> outbound) {
    this.outbound = outbound;
    return this;
  }

  public NodeInfoServices addOutboundItem(String outboundItem) {
    this.outbound.add(outboundItem);
    return this;
  }

   /**
   * Get outbound
   * @return outbound
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getOutbound() {
    return outbound;
  }

  public void setOutbound(List<String> outbound) {
    this.outbound = outbound;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NodeInfoServices nodeInfoServices = (NodeInfoServices) o;
    return Objects.equals(this.inbound, nodeInfoServices.inbound) &&
        Objects.equals(this.outbound, nodeInfoServices.outbound);
  }

  @Override
  public int hashCode() {
    return Objects.hash(inbound, outbound);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NodeInfoServices {\n");
    
    sb.append("    inbound: ").append(toIndentedString(inbound)).append("\n");
    sb.append("    outbound: ").append(toIndentedString(outbound)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

