/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.16.8+97-gee14285
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.gitea.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.DateTime;


/**
 * PullRequestMeta PR info if an issue is a PR
 */
@ApiModel(description = "PullRequestMeta PR info if an issue is a PR")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2022-07-07T10:42:04.488+08:00")
public class PullRequestMeta   {
  @SerializedName("merged")
  private Boolean merged = null;

  @SerializedName("merged_at")
  private DateTime mergedAt = null;

  public PullRequestMeta merged(Boolean merged) {
    this.merged = merged;
    return this;
  }

   /**
   * Get merged
   * @return merged
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getMerged() {
    return merged;
  }

  public void setMerged(Boolean merged) {
    this.merged = merged;
  }

  public PullRequestMeta mergedAt(DateTime mergedAt) {
    this.mergedAt = mergedAt;
    return this;
  }

   /**
   * Get mergedAt
   * @return mergedAt
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getMergedAt() {
    return mergedAt;
  }

  public void setMergedAt(DateTime mergedAt) {
    this.mergedAt = mergedAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PullRequestMeta pullRequestMeta = (PullRequestMeta) o;
    return Objects.equals(this.merged, pullRequestMeta.merged) &&
        Objects.equals(this.mergedAt, pullRequestMeta.mergedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(merged, mergedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PullRequestMeta {\n");
    
    sb.append("    merged: ").append(toIndentedString(merged)).append("\n");
    sb.append("    mergedAt: ").append(toIndentedString(mergedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

