/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.16.8+97-gee14285
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.gitea.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.DateTime;


/**
 * StopWatch represent a running stopwatch
 */
@ApiModel(description = "StopWatch represent a running stopwatch")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2022-07-07T10:42:04.488+08:00")
public class StopWatch   {
  @SerializedName("created")
  private DateTime created = null;

  @SerializedName("duration")
  private String duration = null;

  @SerializedName("issue_index")
  private Long issueIndex = null;

  @SerializedName("issue_title")
  private String issueTitle = null;

  @SerializedName("repo_name")
  private String repoName = null;

  @SerializedName("repo_owner_name")
  private String repoOwnerName = null;

  @SerializedName("seconds")
  private Long seconds = null;

  public StopWatch created(DateTime created) {
    this.created = created;
    return this;
  }

   /**
   * Get created
   * @return created
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getCreated() {
    return created;
  }

  public void setCreated(DateTime created) {
    this.created = created;
  }

  public StopWatch duration(String duration) {
    this.duration = duration;
    return this;
  }

   /**
   * Get duration
   * @return duration
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDuration() {
    return duration;
  }

  public void setDuration(String duration) {
    this.duration = duration;
  }

  public StopWatch issueIndex(Long issueIndex) {
    this.issueIndex = issueIndex;
    return this;
  }

   /**
   * Get issueIndex
   * @return issueIndex
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getIssueIndex() {
    return issueIndex;
  }

  public void setIssueIndex(Long issueIndex) {
    this.issueIndex = issueIndex;
  }

  public StopWatch issueTitle(String issueTitle) {
    this.issueTitle = issueTitle;
    return this;
  }

   /**
   * Get issueTitle
   * @return issueTitle
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getIssueTitle() {
    return issueTitle;
  }

  public void setIssueTitle(String issueTitle) {
    this.issueTitle = issueTitle;
  }

  public StopWatch repoName(String repoName) {
    this.repoName = repoName;
    return this;
  }

   /**
   * Get repoName
   * @return repoName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getRepoName() {
    return repoName;
  }

  public void setRepoName(String repoName) {
    this.repoName = repoName;
  }

  public StopWatch repoOwnerName(String repoOwnerName) {
    this.repoOwnerName = repoOwnerName;
    return this;
  }

   /**
   * Get repoOwnerName
   * @return repoOwnerName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getRepoOwnerName() {
    return repoOwnerName;
  }

  public void setRepoOwnerName(String repoOwnerName) {
    this.repoOwnerName = repoOwnerName;
  }

  public StopWatch seconds(Long seconds) {
    this.seconds = seconds;
    return this;
  }

   /**
   * Get seconds
   * @return seconds
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getSeconds() {
    return seconds;
  }

  public void setSeconds(Long seconds) {
    this.seconds = seconds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StopWatch stopWatch = (StopWatch) o;
    return Objects.equals(this.created, stopWatch.created) &&
        Objects.equals(this.duration, stopWatch.duration) &&
        Objects.equals(this.issueIndex, stopWatch.issueIndex) &&
        Objects.equals(this.issueTitle, stopWatch.issueTitle) &&
        Objects.equals(this.repoName, stopWatch.repoName) &&
        Objects.equals(this.repoOwnerName, stopWatch.repoOwnerName) &&
        Objects.equals(this.seconds, stopWatch.seconds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(created, duration, issueIndex, issueTitle, repoName, repoOwnerName, seconds);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StopWatch {\n");
    
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    issueIndex: ").append(toIndentedString(issueIndex)).append("\n");
    sb.append("    issueTitle: ").append(toIndentedString(issueTitle)).append("\n");
    sb.append("    repoName: ").append(toIndentedString(repoName)).append("\n");
    sb.append("    repoOwnerName: ").append(toIndentedString(repoOwnerName)).append("\n");
    sb.append("    seconds: ").append(toIndentedString(seconds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

