/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.16.8+97-gee14285
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.gitea.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * UserSettingsOptions represents options to change user settings
 */
@ApiModel(description = "UserSettingsOptions represents options to change user settings")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2022-07-07T10:42:04.488+08:00")
public class UserSettingsOptions   {
  @SerializedName("description")
  private String description = null;

  @SerializedName("diff_view_style")
  private String diffViewStyle = null;

  @SerializedName("full_name")
  private String fullName = null;

  @SerializedName("hide_activity")
  private Boolean hideActivity = null;

  @SerializedName("hide_email")
  private Boolean hideEmail = null;

  @SerializedName("language")
  private String language = null;

  @SerializedName("location")
  private String location = null;

  @SerializedName("theme")
  private String theme = null;

  @SerializedName("website")
  private String website = null;

  public UserSettingsOptions description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public UserSettingsOptions diffViewStyle(String diffViewStyle) {
    this.diffViewStyle = diffViewStyle;
    return this;
  }

   /**
   * Get diffViewStyle
   * @return diffViewStyle
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDiffViewStyle() {
    return diffViewStyle;
  }

  public void setDiffViewStyle(String diffViewStyle) {
    this.diffViewStyle = diffViewStyle;
  }

  public UserSettingsOptions fullName(String fullName) {
    this.fullName = fullName;
    return this;
  }

   /**
   * Get fullName
   * @return fullName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getFullName() {
    return fullName;
  }

  public void setFullName(String fullName) {
    this.fullName = fullName;
  }

  public UserSettingsOptions hideActivity(Boolean hideActivity) {
    this.hideActivity = hideActivity;
    return this;
  }

   /**
   * Get hideActivity
   * @return hideActivity
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getHideActivity() {
    return hideActivity;
  }

  public void setHideActivity(Boolean hideActivity) {
    this.hideActivity = hideActivity;
  }

  public UserSettingsOptions hideEmail(Boolean hideEmail) {
    this.hideEmail = hideEmail;
    return this;
  }

   /**
   * Privacy
   * @return hideEmail
  **/
  @ApiModelProperty(example = "null", value = "Privacy")
  public Boolean getHideEmail() {
    return hideEmail;
  }

  public void setHideEmail(Boolean hideEmail) {
    this.hideEmail = hideEmail;
  }

  public UserSettingsOptions language(String language) {
    this.language = language;
    return this;
  }

   /**
   * Get language
   * @return language
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLanguage() {
    return language;
  }

  public void setLanguage(String language) {
    this.language = language;
  }

  public UserSettingsOptions location(String location) {
    this.location = location;
    return this;
  }

   /**
   * Get location
   * @return location
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLocation() {
    return location;
  }

  public void setLocation(String location) {
    this.location = location;
  }

  public UserSettingsOptions theme(String theme) {
    this.theme = theme;
    return this;
  }

   /**
   * Get theme
   * @return theme
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTheme() {
    return theme;
  }

  public void setTheme(String theme) {
    this.theme = theme;
  }

  public UserSettingsOptions website(String website) {
    this.website = website;
    return this;
  }

   /**
   * Get website
   * @return website
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getWebsite() {
    return website;
  }

  public void setWebsite(String website) {
    this.website = website;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserSettingsOptions userSettingsOptions = (UserSettingsOptions) o;
    return Objects.equals(this.description, userSettingsOptions.description) &&
        Objects.equals(this.diffViewStyle, userSettingsOptions.diffViewStyle) &&
        Objects.equals(this.fullName, userSettingsOptions.fullName) &&
        Objects.equals(this.hideActivity, userSettingsOptions.hideActivity) &&
        Objects.equals(this.hideEmail, userSettingsOptions.hideEmail) &&
        Objects.equals(this.language, userSettingsOptions.language) &&
        Objects.equals(this.location, userSettingsOptions.location) &&
        Objects.equals(this.theme, userSettingsOptions.theme) &&
        Objects.equals(this.website, userSettingsOptions.website);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, diffViewStyle, fullName, hideActivity, hideEmail, language, location, theme, website);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserSettingsOptions {\n");
    
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    diffViewStyle: ").append(toIndentedString(diffViewStyle)).append("\n");
    sb.append("    fullName: ").append(toIndentedString(fullName)).append("\n");
    sb.append("    hideActivity: ").append(toIndentedString(hideActivity)).append("\n");
    sb.append("    hideEmail: ").append(toIndentedString(hideEmail)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    theme: ").append(toIndentedString(theme)).append("\n");
    sb.append("    website: ").append(toIndentedString(website)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

